### ISSUE TITLE
generate_tfrecord.py No module named 'object_detection'

### ISSUE THREAD

**Issue by kbrajwani** [pythonlessons/TensorFlow-object-detection-tutorial#2]
Traceback (most recent call last):
  File "generate_tfrecord.py", line 20, in <module>
    from object_detection.utils import dataset_util
ModuleNotFoundError: No module named 'object_detection'

please help i am try to run this code on colab

**Comment by InventivetalentDev** [comment]
This issue helped me: https://github.com/tensorflow/models/issues/2031#issuecomment-317999079

**Comment by IvanNazaruk** [comment]
@kbrajwani 
Copy "object_detection" to the project folder.

Example of a path with a project:
"C:/10_part aim bot with multiprocessing"

**Comment by Jayanth1812** [comment]
I am getting the following errors, when I run the main training program..
(tensorflow) C:\tensorflow\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
Traceback (most recent call last):
File "train.py", line 54, in
from object_detection.builders import model_builder
File "C:\tensorflow\models\research\object_detection\builders\model_builder.py", line 20, in
from object_detection.builders import anchor_generator_builder
File "C:\tensorflow\models\research\object_detection\builders\anchor_generator_builder.py", line 23, in
from object_detection.anchor_generators import flexible_grid_anchor_generator
ModuleNotFoundError: No module named 'object_detection.anchor_generators
