### ISSUE TITLE
   _, ignore_mask = K.control_flow_ops.while_loop(lambda b,*args: b<m, loop_body, [0, ignore_mask]) AttributeError: module 'keras.backend' has no attribute 'control_flow_ops'

### ISSUE THREAD

**Issue by clementks** [pythonlessons/TensorFlow-object-detection-tutorial#4]
Hi, i run into an issue with    _, ignore_mask = K.control_flow_ops.while_loop(lambda b,*args: b<m, loop_body, [0, ignore_mask])
AttributeError: module 'keras.backend' has no attribute 'control_flow_ops' .

I checked online from https://keras.io/backend/ keras.backend whether it has attribute for control_flow_ops. Kindly advise and whether you can send us the revised copy of yolo3/model.py ?

**Comment by pythonlessons** [comment]
This tutorial has nothing with yolo3, why you need it ?
or you wrote to wrong place ?
